name: "PR Title Checker"

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[((DBD)\-[0-9]+|[HOTFIX\-[0-9]+[0-9\.]*[0-9]+)\].*'
      - uses: deepakputhraya/action-branch-name@master
        if: github.base_ref != 'main'
        with:
          regex: '^(feature\/(DBD)\-[0-9]+[\-_]|(hotfix|release)\/[0-9]+[0-9\.]*[0-9]+|main).*'
