name: "Name convention check"

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  checkers:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          # regex: '^(/(APP)\-[0-9]+[\-_]|(hotfix|release)\/[0-9]+[0-9\.]*[0-9]+|main).*'
          regex: '^((APP)\-[0-9]+[\-_]).*'
          allowed_prefixes: "feature,hotfix,release"
          ignore: main
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[((APP)\-[0-9]+|[HOTFIX\-[0-9]+[0-9\.]*[0-9]+)\].*'
