name: app-build

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_REGISTRY: "ghcr.io"
    #   DOCKER_USER: ${{ secrets.DOCKER_USER }}
    #   DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get service name
        uses: xom9ikk/split@v1
        id: repo
        with:
          string: ${{ github.repository }}
          separator: /
          limit: -1
      # - uses: ASzc/change-string-case-action@v2
      #   id: tag
      #   with:
      #     string: ${{ steps.branch.outputs.current_branch }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}
      - name: Additional output
        run: |
          echo service ${{ steps.repo.outputs._1 }}
      # - name: Check branch 2
      #   if: github.ref_name == 'master'
      #   run: echo Branch ${{ github.ref_name }}
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     tags: ${{ env.DOCKER_REGISTRY }}/jsapp:${{ steps.tag.outputs.lowercase }}
      #     push: true
