name: app-build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  SERVICE: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get service version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ${SERVICE}/VERSION
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image
        env:
          ECR: ${{ steps.ecr-login.outputs.registry }}
          TAG: ${{ steps.version.outputs.content }}
        run: |
          docker build -t ${ECR}/${SERVICE}:${TAG} -f ${SERVICE}/Dockerfile ${SERVICE}
          docker push ${ECR}/${SERVICE}:${TAG}
